### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by MzCorona** [phydrus/phydrus#10]
Hello,

I have 6 years of experience with HYDRUS in Academia, so when I came across your phydrus, I was excited to check it out. I downloaded the files, compiled the source code, installed the package and opened it up in Spyder (Python 3.7). Unfortunately, I have not been able to get the code to work. Any chance youhave some suggestions for how to fix this? Below is what Python tells me:

```
**runfile('C:/Users/ccoro/anaconda3/envs/phydrus-master/examples/example.py', wdir='C:/Users/ccoro/anaconda3/envs/phydrus-master/examples')
Traceback (most recent call last):

  File "C:\Users\ccoro\anaconda3\envs\phydrus-master\examples\example.py", line 41, in <module>
    rs = ml.simulate()

  File "C:\Users\ccoro\anaconda3\envs\phydrus-master\phydrus\model.py", line 876, in simulate
    result = run(cmd)

  File "C:\Users\ccoro\anaconda3\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\ccoro\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 105, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\ccoro\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)

  File "C:\Users\ccoro\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)

OSError: [WinError 193] %1 is not a valid Win32 application**

```

I am using a 32-bit python program. I wonder if PHYDRUS is also in 32-bit or if it is in 64-bit? 

Thank you for your time.

**Comment by mvremec** [comment]
Hi @MzCorona,
glad to hear an experienced Hydrus user joined the phydrus community!

From the above, t seems like your "exe" path is set for the Hydrus executable for Mac and Linux ("hydrus"),
The example folder only contains the Hydrus executable for Mac and Linux, the "hydrus.exe" for windows is located in the source folder (our bad). 

You can solve this issue by:
1. copy the "hydrus.exe" from source folder to example folder, and then change:
`exe = os.path.join(os.getcwd(), "hydrus")`
to 
`exe = os.path.join(os.getcwd(), "hydrus.exe")`

I hope this helps!
- please reply if this answer does not help. 
Cheers, Matevz

**Comment by MzCorona** [comment]
It did, thank you! I'm having issues with post-processing but I'll look around before opening up another issue. Thanks again! I look forward to using phydrus.
