### ISSUE TITLE
Connecting with HYDRUS 2D/3D

### ISSUE THREAD

**Issue by HydroCorinna** [phydrus/phydrus#11]
Is there somethling like Phydrus for Hydrus 2D/3D? 
I want calculate every timestep a new BC value depending on the results? How can I do that over the IN and OUT Files?

**Comment by raoulcollenteur** [comment]
Hi @HydroCorinna, not aware of any Python packages for Hydrus 2D/3D ! I think the underlying code is not public. 

Calculating new BC values for every timestep is not something we have done, so can't help there.

Cheers,
Raoul
