### ISSUE TITLE
Number of Print-Times is exceeded !

### ISSUE THREAD

**Issue by martinvonk** [phydrus/phydrus#16]
For my purpose I need daily information on the water content over the entire profile for a period of over 10 years. Therefore tmax>3652 and print_times=True. However Hydrus does not support this many print times and the output file error.msg states:

>  `Number of Print-Times is exceeded !`

I resolved this issue by adjusting the fortran source code (HYDRUS.FOR) and setting the parameter NPD=10000. After recompiling the source code I'am now able to print up to 10000 times in the .out files.

**Comment by martinvonk** [comment]
https://www.pc-progress.com/forum/viewtopic.php?f=4&t=3421

Similar to the issue above.

**Comment by raoulcollenteur** [comment]
@martinvonk & @mvremec can you please recompile after my changes and confirm that this still works for Windows as well?

Also changed some pause statements into prints (aso the fortran code won't stall) ad removed those print time warnings.

**Comment by martinvonk** [comment]
@raoulcollenteur I tested in on both Linux and Windows and it works fine I believe. (For 9862 print_times & 10958 print_times)
I do not get the message `getdat and gettim called but not available` in my anaconda prompt anymore. 

When I (on purpose) "crash" the model (by trying to infiltrate water into a saturated top node) I do not get the message `The numerical solution has not converged ! ` anymore. Also the the run does not stop with the new source code. Both versions do show the following message in anaconda prompt:  `Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG`

**Comment by raoulcollenteur** [comment]
Perfect gonna close this Issue now.

> I do not get the message getdat and gettim called but not available in my anaconda prompt anymore.

That was meant :)
