### ISSUE TITLE
Windows issue. no output files generated

### ISSUE THREAD

**Issue by baramousa** [phydrus/phydrus#19]
Hi I cannot get phydrus to work on windows. i tried it on Linux and it works.

 In windows only the profile, atmosphere in and secelctor are in generated. when i run one of your examples in the cmd i get message that "libquadmath-0.dll" , "libwinpthread-1.dll" and "libgcc-s-seh-1.dll" were not found . I downloaded them but still it wouldn't run. I am susepcting a problem in compiling the source code.  Any suggestions ?

**Comment by raoulcollenteur** [comment]
Did you point the the hydrus.exe file correctly?
