### ISSUE TITLE
Question about Pydrus

### ISSUE THREAD

**Issue by lcy91** [phydrus/phydrus#2]
Hi there,

I just quickly went through posted examples and found all models were created by Pydrus. Just in case, is there a way in Pydrus to read the base model, manually created in Hydrus 1D, and then to modify certain parameters in ATMOSPH.IN?

Thanks,
Chuyang

**Comment by raoulcollenteur** [comment]
Hi @lcy91, We have not yet implemented this option, but would like to be able to do that in the future. However, I think this will take some time as reading in HYDRUS files would not be that straightforward. However, if you have your hydrus model it should not be too hard to make a script using pydrus to recreate the model :)

**Comment by lcy91** [comment]
Hi @raoulcollenteur, Thanks for the speedy reply. I would be glad to apply Pydrus to recreate the base model in future :)
