### ISSUE TITLE
add_root_uptake(model=1). S-shaped van Genuchten root uptake model not implemented yet

### ISSUE THREAD

**Issue by martinvonk** [phydrus/phydrus#24]
`NotImplementedError: Sorry, the S-shaped model has not been implemented yet!`

> if model == 1:
>         raise NotImplementedError("Sorry, the S-shaped model has not been implemented yet!")

[van Genuchten, M. Th., A numerical model for water and solute movement in and below the root zone. Research Report No 121, U.S. Salinity laboratory, USDA, ARS, Riverside, California, 1987.](https://www.pc-progress.com/Documents/RVGenugten/M1987,vG,%20Worm%20USSL%20report.pdf)

Can you please implement this root uptake model?

**Comment by raoulcollenteur** [comment]
Should work now after my last commit. I run some tests and it seems to work for me. You can try:

`ml.add_root_uptake(model=0, p50=-4000, pexp=3, poptm=[-25, -25])
`

Let me know if this works! Also, don't know what p50 should be. van Genugten says: "_pressure head at which the extraction rate is reduced by 50%_". Maybe you can propose a better default (now -800cm).

**Comment by martinvonk** [comment]
I'll try it tomorrow!

From the paper of [Grinevskiy and Pozdniakov - The Use of HYDRUS-1D for Groundwater Recharge Estimation in Boreal Environments](https://www.pc-progress.com/Documents/Workshop_2013_Prague/Proceedings/12_Grinevskiy_and_Pozdnyakov.pdf) table 3 typical values for `p50` (h50) are: 

```
Vegetation type     Forest & Grass
Sand                -15.0m & -24.0m
Loamy sand          -33.3m & -31.9m
Loam                -37.3m & -24.0m

pexp (tau)           2     &  4
```

Off-topic: This paper also (quickly) describes the SURFBAL atmospheric conditions preprocessing @mvremec.

>  SurfBal (Grinevskii and Pozdnyakov, 2010), a special preprocessing code for simulating surface water and energy balances and generating upper boundary conditions for HYDRUS-1D was developed. SurfBal calculates surface water balance using known daily values of precipitation, solar radiation, and maximum and minimum temperatures. It calculates interception by canopy, surface (leaf and snow) evaporation, snow accumulation, consolidation of snowpack and its melting and surface runoff, as well as initial potential values of evaporation, transpiration, and input water fluxes for HYDRUS-1D.

**Comment by raoulcollenteur** [comment]
Let me know if it works. I think -3000 could be a sensible default value then.

**Comment by martinvonk** [comment]
The van Genuchten rootzone model works !. However when running the Feddes root zone model I now get a Error.msg file stating :  ` Error when reading from an input file Selector.in Sink Informations ! `

**Comment by raoulcollenteur** [comment]
Thanks, small mistake with some tuples 😆 

Should work now after my last commit.
