### ISSUE TITLE
API-docs

### ISSUE THREAD

**Issue by baramousa** [phydrus/phydrus#27]
Hi i think in your last update you removed instructions of the commands of phydrus. You had detailed description of what to enter and how for all the commands.

**Comment by raoulcollenteur** [comment]
Hi Baramousa,

Thanks for noticing! Indeed something went wrong with ReadTheDocs with the API documentation, will fix it later this week. The documentation website is getting a big update right know so please wait a few days :)

Cheers,
Raoul

**Comment by raoulcollenteur** [comment]
@baramousa , just fixed it, check out the new (hopefully better) API Docs here: https://phydrus.readthedocs.io/en/latest/api/index.html

**Comment by baramousa** [comment]
ja . thanks for the quick response.
