### ISSUE TITLE
Version 0.0.2

### ISSUE THREAD

**Issue by malotine** [phydrus/phydrus#4]
Hi I was wondering if version 0.0.2 was already avilable for download.
Thanks in advance, 
Ines

**Comment by raoulcollenteur** [comment]
Hi Ines, 
The version on Pypi is actually outdated and the code here on GitHub contains a lot of new features/code. I will update this later this week, and also rename the package to Phydrus. We're currently working to get a more stable version so Phydrus is definitely in development phase for another two months I think. But it should already work many applications and we're happy to receive feedback on the project if you have some :)

**Comment by malotine** [comment]
Hi Raoul,


Thanks a lot for your quick answer. I'm glad to know that the code will be updated soon. I'll be happy to give you all the feedback I have on the project.


________________________________

**Comment by raoulcollenteur** [comment]
Hi @malotine ! Took a bit longer. The project had to be renamed to Phydrus, so it was a little more work. However this is the final name :)

Updated to 0.1.0. The first real release actually. Hope you like it, feedback always welcome !

**Comment by malotine** [comment]
Hi Raoul,

Thanks a lot for the feedback. I’m using directly HUDRUS for the moment but I might have a look at Phydrus later on.
Best regards,
Ines
