### ISSUE TITLE
logo wrong?

### ISSUE THREAD

**Issue by JannisHoch** [phydrus/phydrus#6]
Dear developers,

while the model/module is called 'phydrus', the logo of your works says 'pydrus' - am I missing here something and that has a purpose or is indeed the 'h' missing?

Best, Jannis

**Comment by raoulcollenteur** [comment]
Hi Jannis! Yes you are right, still need to change the logo to the new name. We started with Pydrus but renamed (almost) everything to Phydrus now ;)

**Comment by raoulcollenteur** [comment]
Finally solved this issue with a temporary logo.
