### ISSUE TITLE
Meaning of the atmosphere data in Example 1

### ISSUE THREAD

**Issue by Mew-YL** [phydrus/phydrus#65]
Hi, I'm little confused about the meaning for each column of the atmosphere data in Example 1.
What are the meanings of variables tAtm,Prec,rSoil,rRoot,hCritA exactly?

**Comment by martinvonk** [comment]
https://github.com/phydrus/phydrus/blob/624740c818432b3e0fdc324238a69714e4981b6e/phydrus/model.py#L425-L437
