### ISSUE TITLE
"print_times" arguement seems to not be working correctly

### ISSUE THREAD

**Issue by tomglose** [phydrus/phydrus#8]
Hey guys,

I was trying to have the T_LEVEL.OUT file contain values at my specified print times using the "print_array" argument but the file always ends up containing values for every time step. I looked through the SELECTOR.IN file and saw that the "lPrint" flag is set to true even when I have "print_times = False" in the arguments of "add_time_info". 

I found a potential fix by moving the "self.time_info" block of code (lines 105-122 in model.py) to below the "add_time_info" function definition and changed the dictionary value for "lPrint" from "True" to "print_times". 

Cheers!
Tom

**Comment by raoulcollenteur** [comment]
Hi Tom,

Thanks for the heads up on this bug, we still need to look a little bit better into how to deal with time I think. If you want you can do a PR with the proposed change ?

I think we had some issues in some of the examples when using the print_times, but not sure here. I'll look into hopefully within a few weeks... I have you find any other issues, please keep reporting them :)

Cheers, Raoul

**Comment by tomglose** [comment]
Just submitted the pull request! I mentioned this on the pull request but also wanted to here, I did accidentally commit the updated file to the master repository and I can't figure out how to remove it.

As I keep using phydrus I will submit bugs if I come across them!

Thanks,
Tom

**Comment by raoulcollenteur** [comment]
Sorry this slipped through this week, I'll look at it beginning of next week!

**Comment by raoulcollenteur** [comment]
Two months later... Sorry for that, just merged the PR. Will be working on more changes from next week onwards again :)
