### ISSUE TITLE
Meteorological parameter import issue

### ISSUE THREAD

**Issue by jingliu0217** [phydrus/phydrus#81]
Dear Phydrus team, 
    
    Recently, I have had some questions while using this package. When I use the official software (Hydrus-1D), I need to input meteorological data, such as maximum temperature, minimum temperature, wind speed, relative humidity and other parameters. However, I did not find the corresponding interface in Phydrus. 
    So, my question is how should the above parameters be passed into the model for processing. 
    Looking forward to your reply. 
    Jing

**Comment by martinvonk** [comment]
You can calculate the potential evaporation yourself using [pyET](https://github.com/pyet-org/pyet) where you can input the meteorological data, such as maximum temperature, minimum temperature, wind speed, relative humidity and other parameters.

**Comment by jingliu0217** [comment]
ok, got it. thank you very much
